services:
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    # Using the 'build' context allows Docker to cache the image.
    # It will only "rebuild" if you change the Dockerfile.
    volumes:
      - .:/app
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
