<?php

declare(strict_types=1);

namespace Victormgomes\LaravelQueryEngine\Traits;

use Victormgomes\LaravelQueryEngine\Rules;
use Victormgomes\LaravelQueryEngine\Support\ModelRegistry;

trait HasQueryEngineRules
{
    /**
     * Get the validation rules generated by Laravel Query Engine.
     */
    public function rules(): array
    {
        $fqcn = ModelRegistry::resolveFrom($this);

        return $fqcn !== null ? Rules::generate($fqcn) : [];
    }
}
